version: "3.8"

services:

    api:
        build: ./docker/app
        ports:
          - 8000:8000
        environment:
            - DB_URL=mongodb://db/myTestDB
        volumes:
            - ./app:/app

        command: uvicorn main:app --host 0.0.0.0 --reload
        #command: sleep infinity

    db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - datavolume:/data/db
volumes:
    datavolume:
